import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const components = readFileSync(join(root, 'src/theme/components.css'), 'utf8')
const tokens = readFileSync(join(root, 'src/theme/tokens.css'), 'utf8')
const motion = readFileSync(join(root, 'src/theme/motion.css'), 'utf8')
const surfaces = readFileSync(join(root, 'src/theme/taffy-surfaces.css'), 'utf8')
const badges = readFileSync(join(root, 'src/theme/taffy-badges.css'), 'utf8')
const metrics = readFileSync(join(root, 'src/client/conversation-metrics.ts'), 'utf8')
const client = readFileSync(join(root, 'src/client/index.ts'), 'utf8')
const mount = readFileSync(join(root, 'src/client/mount.ts'), 'utf8')
const resolve = readFileSync(join(root, 'src/assets/resolve.ts'), 'utf8')
const userTheme = readFileSync(join(root, 'src/theme/user-theme.ts'), 'utf8')

describe('decorative CSS contracts', () => {
  it('does not trap the official settings overlay in a sidebar stacking context', () => {
    expect(components).not.toMatch(/sidebarCol[\s\S]{0,180}isolation:\s*isolate/)
    expect(components).not.toMatch(/\[id='root'\][\s\S]{0,80}z-index:\s*2/)
  })

  it('keeps the settings dialog opaque without stealing DSH stacking', () => {
    expect(components).toContain("[data-slot='sidebar.settings'] [role='dialog'][aria-modal='true']")
    expect(components).not.toContain('z-index: 1000')
    expect(components).not.toMatch(/sidebar.settings[\s\S]{0,160}pointer-events:\s*auto/)
    expect(components).toContain('pointer-events: none')
  })

  it('wires low-power mode from settings and motion prefs', () => {
    expect(mount).toContain("toggleAttribute('data-taffy-low-power'")
    expect(mount).toContain('shouldUseLowPower')
  })

  it('does not change official composer stacking', () => {
    expect(components).not.toMatch(/composer-seat[\s\S]{0,80}z-index/)
    expect(components).not.toContain("[data-phase='hero']")
  })

  it('places independent left and right character layers behind a curtain veil', () => {
    expect(components).toContain("[data-taffy-character='left']")
    expect(components).toContain("[data-taffy-character='right']")
    expect(components).toContain("[data-taffy-veil='curtain']")
    expect(components).toContain('opacity: 1')
    expect(components).toContain('max-width: none')
    expect(components).toContain('clamp(520px, 88vh, 1080px)')
    expect(components).toMatch(/translate:\s*calc\(var\(--taffy-conversation-left[\s\S]{0,80}\+\s*clamp\(/)
    expect(components).not.toContain('- 128px')
    expect(components).not.toContain('opacity: 0.34')
    expect(components).not.toContain('opacity: 0.86')
    expect(components).toContain('--taffy-right-panel-width')
    expect(badges).toContain("[data-skin-chrome='sidebar-trim']")
    expect(badges).toContain("[data-skin-chrome='taffy-top-curtain']")
    expect(badges).toContain("[data-skin-chrome='taffy-bottom-curtain']")
    expect(badges).toContain("[data-taffy-frame-badge]")
    expect(badges).toContain("[data-taffy-frame-corners]")
    expect(badges).toContain("[data-taffy-sidebar-ornament='ribbon']")
    expect(badges).toContain("[data-taffy-sidebar-ornament='swag']")
    expect(components).toContain("[data-taffy-sparkles]")
    expect(components).toContain("[data-taffy-pose='sit']")
    expect(mount).toContain('scenePoses')
  })

  it('specializes chrome icons with distinct Q-version overlays', () => {
    expect(components).toContain('--taffy-q-send')
    expect(components).toContain('--taffy-q-settings')
    expect(components).toContain('--taffy-q-brand')
    expect(components).toContain('--taffy-q-brand-right')
    expect(components).toContain("button[aria-label='发送消息']")
    expect(components).toContain("button[aria-haspopup='dialog']")
    expect(components).toContain("button[class*='brand']")
    expect(motion).toContain('taffy-send-glow')
  })

  it('hides top sidebar frame corners so they do not stack on the brand Q', () => {
    expect(badges).toContain("[data-taffy-sidebar-corner='top-left']")
    expect(badges).toContain("[data-taffy-sidebar-corner='top-right']")
    expect(badges).toMatch(/sidebar-corner='top-left'\][\s\S]{0,80}display:\s*none/)
    expect(badges).toMatch(/sidebar-corner='top-right'\][\s\S]{0,80}display:\s*none/)
  })

  it('scopes native DSH tokens to app columns instead of body', () => {
    const bodyRule = tokens.match(/body\[data-dsh-taffy-theme\] \{[\s\S]*?\n\}/)
    expect(bodyRule?.[0]).not.toMatch(/--dsw-/)
    expect(tokens).toContain("[class*='sidebarCol']")
    expect(tokens).toContain('--dsw-alias-label-primary: var(--ds-taffy-text)')
    expect(tokens).toContain('--ds-taffy-text: #fff3e8')
    expect(tokens).toContain('--ds-taffy-text: #141018')
    expect(tokens).toContain('--dsw-specific-sidebar-fill')
    expect(components).toContain("[data-chat-flow]")
    expect(components).toContain('--dsw-alias-label-primary: var(--ds-taffy-text)')
    expect(components).toContain('text-shadow: var(--taffy-text-halo)')
    expect(tokens).toContain('--taffy-text-halo')
    expect(components).toContain(':is(body[data-dsh-taffy-theme], [data-dsh-taffy-settings]) .dsh-taffy-general-cube')
    expect(components).toContain('calc(var(--taffy-veil-opacity, 0.12) * 130%)')
    expect(tokens).not.toContain('--taffy-veil-opacity: 0.18')
    expect(tokens).not.toContain('--taffy-veil-opacity: 0.08')
  })

  it('gives plugin surfaces an acrylic whitelist instead of global Canvas boards', () => {
    expect(surfaces).toContain('[data-taffy-surface=\'acrylic\']')
    expect(surfaces).toContain("[data-plugin-root][data-taffy-acrylic='standard']")
    expect(surfaces).toContain("[data-plugin-root][data-taffy-acrylic='soft']")
    expect(surfaces).not.toContain("[data-plugin-root][data-taffy-acrylic]:not([data-taffy-acrylic='off'])")
    expect(surfaces).not.toContain('position: relative')
    expect(surfaces).not.toContain('[data-shell-overlay] > *')
    expect(surfaces).not.toContain('[data-dsh-floating-panel]')
    expect(surfaces).not.toContain('[data-dsh-better-sidebar]')
    expect(surfaces).not.toContain("[data-pane='details']")
    expect(surfaces).not.toContain('[data-cordis-panel]')
    expect(surfaces).not.toMatch(/^body \*$/m)
    expect(components).not.toContain('background-color: var(--dsw-alias-bg-layer-2, Canvas)')
    expect(components).not.toContain("[data-skin-chrome='sidebar-mascot']")
    expect(components).not.toMatch(/detailsCol[\s\S]{0,240}backdrop-filter/)
    expect(components).not.toContain('clip-path')
    expect(components).toContain('[data-taffy-q-ready]')
    expect(components).toContain('background-size: 118% 118%')
    expect(components).toContain('background-size: 122% 122%')
    expect(components).toContain('width: 42px')
    expect(components).toContain('width: 36px')
    expect(components).not.toContain('background-size: 76%')
    expect(components).not.toContain('background-size: contain')
    expect(components).toContain("[class*='brand']")
    expect(components).not.toMatch(/button\s*\{[^}]*border-radius:\s*50%/)
    expect(components).toContain('rgba(255, 247, 241, 0.16)')
    expect(components).toContain('rgba(33, 27, 50, 0.22)')
    expect(components).toContain(":has(> [class*='sidebarCol']):has(> [class*='centerCol'])")
    expect(tokens).toContain(":has(> [class*='sidebarCol']):has(> [class*='centerCol'])")
    expect(tokens).not.toMatch(/\[id='root'\][\s\S]{0,120}isolation:\s*isolate/)
    expect(components).toContain("[data-taffy-veil='curtain']")
    expect(components).toContain("[data-taffy-mascot='sidebar']")
    expect(components).toContain('border-radius: 50%')
    expect(components).not.toMatch(/button\s*\{[^}]*border-radius:\s*50%/)
    expect(motion).toContain("[data-taffy-veil='curtain']")
  })

  it('binds the stage frame to chat-flow width and scroll viewport height', () => {
    expect(badges).toContain('--taffy-content-left')
    expect(badges).toContain('--taffy-content-width')
    expect(badges).toContain('--taffy-viewport-top')
    expect(badges).toContain('--taffy-viewport-height')
    expect(badges).toMatch(/atelier-frame[\s\S]{0,2000}transition:\s*none/)
    expect(badges).toContain('--taffy-conversation-content-left')
    expect(badges).toContain('pointer-events: none')
    expect(badges).not.toContain('z-index: 1000')
    expect(badges).not.toMatch(/var\(--taffy-details-width/)
    expect(metrics).toContain('getBoundingClientRect')
    expect(metrics).toContain('ResizeObserver')
    expect(metrics).toContain('CONVERSATION_SCROLL_SELECTOR')
    expect(metrics).toContain('CHAT_FLOW_SELECTOR')
    expect(client).toContain('startConversationMetrics')
    expect(client).toContain('createChromeObserver')
    expect(mount).toContain('taffy-top-curtain')
    expect(mount).toContain('taffy-bottom-curtain')
    expect(mount).toContain('createStageCurtains')
    expect(badges).toContain('--taffy-frame-left')
    expect(badges).toContain('--taffy-frame-width')
    expect(badges).toContain('--taffy-content-left')
    expect(tokens).toContain('--taffy-frame-opacity')
    expect(tokens).toContain('--taffy-panel-opacity')
    expect(tokens).toContain('--taffy-veil-opacity')
  })
})

describe('lifecycle contracts', () => {
  it('updates art in place instead of remounting chrome on every settings change', () => {
    expect(client).toContain('syncStageArt')
    expect(client).toContain('mountStaticChrome')
    expect(client).toContain('ensureChrome')
    expect(client).not.toContain('const mountChrome')
    expect(client).toContain('removeOwnedChrome')
  })

  it('uses the dark right figure in night mode', () => {
    expect(resolve).toContain('BUNDLED_RIGHT_DARK')
    expect(resolve).toContain('BUNDLED_RIGHT_LIGHT')
    expect(resolve).toMatch(/night \? BUNDLED_RIGHT_DARK : BUNDLED_RIGHT_LIGHT/)
    expect(resolve).toContain('BUNDLED_AVATAR_NIGHT')
    expect(readFileSync(join(root, 'src/client/bundled-assets.ts'), 'utf8')).toContain('buildAssetUrl')
  })

  it('never writes or removes official --dsw tokens from applyThemeTokens', () => {
    expect(userTheme).not.toMatch(/--dsw-alias/)
    expect(userTheme).toContain("setProperty('--ds-taffy-pink'")
  })
})
