/** DSH public DOM API selectors — single source of truth for chrome hooks. */
export declare const SKIN_OWNER = "dsh-taffy-theme";
export declare const SIDEBAR_SELECTOR = ":is([data-pane='sidebar'], [class*='sidebarCol'])";
export declare const DETAILS_SELECTOR = ":is([data-pane='details'], [class*='detailsCol'], [class*='_explorer']:not([class*='Body']):not([class*='body']))";
export declare const CONVERSATION_SELECTOR = ":is([data-pane='conversation'], [class*='centerCol'])";
export declare const HERO_SELECTOR = "[data-phase='hero']";
export declare const ACTIVE_SELECTOR = "[data-phase='active']";
export declare const CHAT_FLOW_SELECTOR = "[data-chat-flow]";
export declare const CONVERSATION_SCROLL_SELECTOR = "[data-conversation-scroll]";
export declare const COMPOSER_OVERLAY_SELECTOR = "[data-conversation-composer-overlay]";
export declare const COMPOSER_CARD_SELECTOR = "[data-composer-card]";
export declare const INPUT_MIRROR_SELECTOR = "[data-input-mirror]";
export declare const SETTINGS_DIALOG_SELECTOR = "[data-slot='sidebar.settings'] [role='dialog'][aria-modal='true']";
export declare const TITLEBAR_SELECTOR = "[class*='titlebar'], header:has([role='tablist'])";
export declare const WORKSPACE_SELECTOR = "header [role='tablist']";
export declare const BETTER_SIDEBAR_SELECTOR = "[data-dsh-better-sidebar]";
export declare const RIGHT_DOCK_SELECTOR: string;
export declare const SIDEBAR_HEADER_SLOT = "[data-slot='sidebar.header']";
export declare const TOOL_CALL_SELECTOR = "[data-tool-call]";
export declare const STREAMING_SELECTOR = "[data-streaming=\"true\"]";
