import type { TaffySettings } from '../state/types';
export declare const STORAGE_KEY = "dsh-taffy-theme:v1";
export declare const SETTINGS_CHANGE_EVENT = "dsh-taffy-theme:settings-change";
declare const LEGACY_VEILS: readonly ["thin", "standard", "thick"];
type LegacyVeil = (typeof LEGACY_VEILS)[number];
export declare function veilFromOpacity(percent: number): LegacyVeil;
export declare function veilBucket(settings: Pick<TaffySettings, 'veilOpacity'>): LegacyVeil;
export declare function loadSettings(): TaffySettings;
export declare function saveSettings(next: TaffySettings): void;
export declare function subscribeSettings(onChange: (settings: TaffySettings) => void): () => void;
export {};
